//
//  EndPoints.swift
//  Tickt
//
//  Created by Admin on 05/03/21.
//

enum EndPoint : String {
    
    static let apiBaseUrl = "\(stagingUrl)/"
    static let qaUrl = "https://ticktqaapi.appskeeper.in/v1"
    static let devUrl = "https://ticktdevapi.appskeeper.in/v1"
    static let liveUrl = "https://ticktstgapi.appskeeper.in/v1"
    static let stagingUrl = "https://ticktstgapi.appskeeper.in/v1"
    
    case login = "auth/login"
    case signup = "auth/signup"
    case logout = "auth/logout"
    case uploadDocument = "upload/"
    case tradeList = "auth/tradeList"
    case verifyOTP = "auth/verifyOTP"
    case termsAndCondition = "auth/tnc"
    case socialLogin = "auth/socialAuth"
    case jobTypeList = "auth/jobTypeList"
    case privacyPolicy = "auth/privacyPolicy"
    case createPassword = "auth/createPassword"
    case forgotPassword = "auth/forgot_password"
    case verifyMobileOtp = "auth/verifyMobileOtp"
    case getRecentSearch = "admin/getRecentSearch"
    case checkEmailId = "auth/checkEmailId?email="
    case checkSocialId = "auth/checkSocialId?socialId="
    case deleteRecentSearch = "admin/deleteRecentSearch"
    case verifySocialAccount = "auth/verify-social-account"
    case getSearchedData = "admin/getSearchData?search_text="
    case checkMobileNumber = "auth/checkMobileNumber?mobileNumber="
           
    case jobList = "job/jobList"
    case recommendedJob = "home"
    case applyJob = "home/apply"
    case saveJob = "home/saveJob"
    case jobSearch = "home/search"
    case homeSearch = "/home/search"
    case jobDetails = "home/jobDetails"
    case nearByJob = "home/viewNearByJob"
    case readNotification = "home/unReadNotification"
    
    case addItem = "quote/addItem"
    case addQuote = "quote/addQuote"
    case deleteItem = "quote/deleteItem"
    case updateItem = "quote/updateItem"

    case jobCreate = "job/create"
    case saveTemplate = "job/createTemplate"
    case jobTempMilestoneList = "job/tempMilestoneList"
    case jobBuilderPublishJobAgain = "job/builder/publishJobAgain"
    case profileBuilderDeleteTemplate = "profile/builder/deleteTemplate"
        
    case cancelJob = "job/tradie/cancelJob"
    case newJobList = "job/tradie/newJobList"
    case askQuestion = "job/tradie/askQuestion"
    case getQuestion = "job/tradie/questionList"
    case tradieVouchers = "job/tradie/getVoucher"
    case pastJobsTradie = "job/tradie/pastJobList"
    case milestoneList = "job/tradie/milestoneList"
    case editQuestion = "job/tradie/updateQuestion"
    case activeJobDetails = "job/tradie/jobDetails"
    case reviewBuilder = "job/tradie/reviewBuilder"
    case getBuilderReviews = "job/tradie/reviewList"
    case tradieReviewReply = "job/tradie/reviewReply"
    case getBuilderJobs = "job/tradie/getBuildersJob"
    case deleteQuestion = "job/tradie/deleteQuestion"
    case activeJobsTradie = "job/tradie/activeJobList"
    case completeMilestone = "job/tradie/markComplete"
    case lodgeDisputeTradie = "job/tradie/lodgeDispute"
    case appliedJobsTradie = "job/tradie/appliedJobList"
    case removeReview = "job/tradie/removeReviewBuilder"    
    case viewBuilderProfile = "job/tradie/builderProfile"
    case updateReviewReply = "job/tradie/updateReviewReply"
    case removeReviewReply = "job/tradie/removeReviewReply?"
    case replyCancelRequest = "job/tradie/replyCancellation"
    case replyChangeRequest = "job/tradie/replyChangeRequest"
    case approvedMilestone = "job/tradie/approveMilestoneList"
    case acceptRejectInvitaion = "job/tradie/acceptDeclineInvitation"
    
    case openJobDetails = "job/builder/jobDetails"
    case getQuestionsBuilder = "job/builder/questionList"
    case jobBuilderAnswerQuestion = "job/builder/answerQuestion"
    case jobBuilderUpdateAnswer = "job/builder/updateAnswer"
    case jobBuilderDeleteAnswer = "job/builder/deleteAnswer"
    case openJobsBuilder = "job/builder/openJobList"
    case pastJobsBuilder = "job/builder/pastJobList"
    case activeJobsBuilder = "job/builder/activeJobList"
    case needApprovalListing = "job/builder/needApproval"
    case newApplicantListing = "job/builder/newApplicants"
    case jobBuilderMilestoneList = "job/builder/milestoneList"
    case jobBuilderChangeRequest = "job/builder/changeRequest"
    case jobBuilderRemoveReviewTradie = "job/builder/removeReviewTradie"
    
    case jobRepublishJob = "job/republishJob"
    case templateList = "profile/builder/templatesList"
    case getBankDetails = "profile/tradie/getBankDetails"
    case addBankDetails = "profile/tradie/addBankDetails"
    case jobBuilderReviewTradie = "job/builder/reviewTradie"
    case jobBuilderTradieProfile = "job/builder/tradieProfile"
    case updateBankDetails = "profile/tradie/updateBankDetails"
    case deleteBankDetails = "profile/tradie/removeBankDetails"
    case jobBuilderMilestoneDetails = "job/builder/milestoneDetails"
    case jobBuilderAcceptDeclineRequest = "job/builder/acceptDeclineRequest"
    case jobBuilderNewJobApplicationList = "job/builder/newJobApplicationList"
    case jobBuilderCancelJob = "job/builder/cancelJob"
    case lodgeDisputeBuilder = "job/builder/lodgeDispute"
    case jobBuilderSaveTradie = "job/builder/saveTradie"
    case jobBuilderChooseJob = "job/builder/chooseJob"
    case jobBuilderInviteForJob = "job/builder/inviteForJob"
    case jobBuilderCancelInviteForJob = "job/builder/cancelInviteForJob"
    case jobBuilderMilestoneApproveDecline = "job/builder/milestoneApproveDecline"
    case jobBuilderReviewList = "job/builder/reviewList"
    case jobBuilderGetVoucher = "job/builder/getVoucher"
    case jobBuilderAddVoucher = "job/builder/addVoucher"
    case jobBuilderUpdateReviewTradie = "job/builder/updateReviewTradie"
    case profileBuilderGetSavedTradies = "profile/builder/getSavedTradies"
    case profileBuilderChangePassword = "profile/builder/changePassword"
    case profileBuilder = "profile/builder"
    case profileBuilderGetBasicDetails = "profile/builder/getBasicDetails"
    case profileBuilderView = "profile/builder/view"
    case profileBuilderGetAllJobs = "profile/builder/getAllJobs"
    case jobBuilderReviewReplyGive = "job/builder/reviewReplyGive"
    case jobBuilderReviewReply = "job/builder/reviewReply"
    case profileBuilderEditBasicDetails = "profile/builder/editBasicDetails"
    case jobBuilderUpdateReviewReply = "job/builder/updateReviewReply"
    case jobBuilderRemoveReviewReply = "job/builder/removeReviewReply"
    case profileBuilderEditProfile = "profile/builder/editProfile"
    case profileBuilderUserImage = "profile/builder/userImage"
    case profileBuilderDeleteProtfolio = "profile/builder/deleteProtfolio"
    case homeTradieProfile = "home/tradieProfile"
    case homeInvitedJobIds = "home/invitedJobIds"
    case profileBuilderChangeEmail = "profile/builder/changeEmail"
    case profileBuilderVerifyEmail = "profile/builder/verifyEmail"
    case paymentBuilderAddNewCard = "payment/builder/addNewCard"
    case paymentBuilderCardList = "payment/builder/cardList"
    case profileBuilderSettings = "profile/builder/settings"
    case builderTermsAndCondition = "profile/builder/tnc"
    case builderPrivacyPolicy = "profile/builder/privacyPolicy"
    case paymentBuilderPay = "payment/builder/pay"
    case paymentBuilderUpdateCard = "payment/builder/updateCard"
                    
    //Profile Tradie
    case tradieProfile = "profile/tradie"
    case savedJobs = "profile/tradie/getSavedJobs"
    case tradieRevenue = "profile/tradie/myRevenue"
    case tradiePublicProfile = "profile/tradie/view"
    case uploadUserImage = "profile/tradie/userImage"
    case addPortfolio = "profile/tradie/addPortfolio"
    case revenueDetail = "profile/tradie/revenueDetail"    
    case tradieTermsAndCondition = "profile/tradie/tnc"
    case editPortfolio = "profile/tradie/editPortfolio"
    case editTradieProfile = "profile/tradie/editProfile"
    case profileTradieSettings = "profile/tradie/settings"
    case tradiePrivacyPolicy = "profile/tradie/privacyPolicy"
    case tradieBasicDetails = "profile/tradie/getBasicDetails"
    case tradieChangePassword = "profile/tradie/changePassword"
    case profileTradieChangeEmail = "profile/tradie/changeEmail"
    case profileTradieVerifyEmail = "profile/tradie/verifyEmail"
    case deleteTradiePortfilio = "profile/tradie/deletePortfolio"
    case editTradieBasicDetails = "profile/tradie/editBasicDetails"
    case profileTradieGetSettingsData = "profile/tradie/getSettingsData"
    case authAddDeviceToken = "auth/addDeviceToken"
    
    case jobBuilderVouchesJob = "job/builder/vouchesJob"
    case paymentBuilderDeleteCard = "payment/builder/deleteCard"
    case jobBuilderReplyCancellation = "job/builder/replyCancellation"
    case profileBuilderGetSettingsData = "profile/builder/getSettingsData"
    case paymentBuilderLastUsedCard = "payment/builder/lastUsedCard"
    case profileBuilderSupport = "profile/builder/support"
    case homeNotification = "home/notification"
    case jobEditTemplate = "job/editTemplate"
    case profileBuilderMyRevenue = "profile/builder/myRevenue"
    case profileBuilderRevenueDetail = "profile/builder/revenueDetail"
    case quoteListing = "quote/quoteByJobId"
    case removeQuoteJob = "job/remove"
    case openQuoteJobDetails = "job/getOpenJobDetails"
    case jobUpdate = "job/update"
    case idUpload = "payment/uploadStripeDocument"
    case closeTheJob = "job/closeQuoteJob"
    case cancelOpenJob = "job/cancelOpenJob"
    case payment_createClientSecretKey = "payment/createClientSecretKey"
    
    case job_tradie_answer = "job/tradie/answer"
    case job_builder_answer = "job/builder/answer"
    
    var path : String {
        let url = EndPoint.apiBaseUrl
        return url + self.rawValue
    }
}

